In [1]:
import pandas as pd
import numpy as np
import os

In [3]:
# create path
path = r'C:\Users\kthav\My Pc\Desktop\Career Foundry\Data Immersion\Python Fundamentals for Data Analytics\11-12-2024 Instacart Basket Analysis'

In [5]:
path

'C:\\Users\\kthav\\My Pc\\Desktop\\Career Foundry\\Data Immersion\\Python Fundamentals for Data Analytics\\11-12-2024 Instacart Basket Analysis'

In [9]:
# import instacart_orders_products_customers_merged.pkl as df_opcm
df_opcm = pd.read_pickle(os.path.join(path, 'Data', 'Prepared Data', 'instacart_orders_products_customers_merged.pkl'))

In [11]:
df_opcm.head(10)

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,first_order,product_id,add_to_cart_order,reordered,...,frequency_flag,first_name,surname,gender,state,age,date_joined,dependants,marital_status,income
0,2539329,1,1,2,8,NaN,True,196,1,0,...,Non-frequent customer,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423
1,2539329,1,1,2,8,NaN,True,14084,2,0,...,Non-frequent customer,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423
2,2539329,1,1,2,8,NaN,True,12427,3,0,...,Non-frequent customer,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423
3,2539329,1,1,2,8,NaN,True,26088,4,0,...,Non-frequent customer,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423
4,2539329,1,1,2,8,NaN,True,26405,5,0,...,Non-frequent customer,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423
5,2398795,1,2,3,7,15.0,False,196,1,1,...,Non-frequent customer,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423
6,2398795,1,2,3,7,15.0,False,10258,2,0,...,Non-frequent customer,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423
7,2398795,1,2,3,7,15.0,False,12427,3,1,...,Non-frequent customer,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423
8,2398795,1,2,3,7,15.0,False,13176,4,0,...,Non-frequent customer,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423
9,2398795,1,2,3,7,15.0,False,26088,5,1,...,Non-frequent customer,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423

In [13]:
column_names = df_opcm.columns.tolist()
print(column_names)

['order_id', 'user_id', 'order_number', 'orders_day_of_week', 'order_hour_of_day', 'days_since_last_order', 'first_order', 'product_id', 'add_to_cart_order', 'reordered', 'product_name', 'aisle_id', 'department_id', 'prices', '_merge', 'busiest_day', 'busiest days', 'busiest_period_of_day', 'max_order', 'loyalty_flag', 'average_spend', 'spender_flag', 'customer_frequency', 'frequency_flag', 'first_name', 'surname', 'gender', 'state', 'age', 'date_joined', 'dependants', 'marital_status', 'income']

In [15]:
df_opcm.drop(columns=['_merge'], inplace=True)

In [19]:
# import instacart_orders_products_customers_merged.pkl as df_opcm
dept = pd.read_csv(os.path.join(path, 'Data', 'Prepared Data', 'departments_cleaned.csv'))

In [21]:
dept

    Unnamed: 0  department_id       department
0            0              1           frozen
1            1              2            other
2            2              3           bakery
3            3              4          produce
4            4              5          alcohol
5            5              6    international
6            6              7        beverages
7            7              8             pets
8            8              9  dry goods pasta
9            9             10             bulk
10          10             11    personal care
11          11             12     meat seafood
12          12             13           pantry
13          13             14        breakfast
14          14             15     canned goods
15          15             16       dairy eggs
16          16             17        household
17          17             18           babies
18          18             19           snacks
19          19             20             deli
20          20             21          missing

In [23]:
dept.drop(columns=['Unnamed: 0'], inplace=True)

In [29]:


# Merge df_opcm with dept on department_id
final = df_opcm.merge(dept, on='department_id', how='inner')

MemoryError: Unable to allocate 3.36 GiB for an array with shape (14, 32246709) and data type int64